ENV NCCL_SOCKET_IFNAME='hsn0,hsn1,hsn2,hsn3'
ENV NCCL_NET_GDR_LEVEL=PHB

#
# Check https://support.hpe.com/hpesc/public/docDisplay?docId=dp00004854en_us&docLocale=en_US for details
#
ENV FI_MR_CACHE_MONITOR=userfaultfd
ENV FI_CXI_DEFAULT_CQ_SIZE=131072
# These deteriorate performance to lower node count:
# ENV FI_CXI_RX_MATCH_MODE=software
# ENV FI_CXI_RDZV_PROTO=alt_read
# # Increase for larger jobs
# ENV FI_CXI_REQ_BUF_SIZE=256
